import { describe, expect, it } from "vitest";
import { acceptPendingDraw, canPlayCard, CardColor, createGame, drawCard, GameState, playCard, playCards, selectWildColor, UnoCard } from "./engine";

let id = 0;
const card = (color: CardColor | null, value: UnoCard["value"]): UnoCard => ({ id: `test-${id++}`, color, value });
function state(hand: UnoCard[], top = card("yellow", "6")): GameState {
  return { players: [{ id: "you", name: "You", hand }, { id: "lena", name: "Lena", hand: [] }, { id: "milo", name: "Milo", hand: [] }], drawPile: Array.from({ length: 20 }, () => card("red", "1")), discardPile: [top], currentPlayerIndex: 0, direction: 1, activeColor: top.color!, pendingDrawCount: 0, drawStackType: null, gameStatus: "playing", winnerId: null, awaitingColorFor: null, hasDrawnCard: false, selectedComboCards: [] };
}

describe("UNO engine", () => {
  it.each([["yellow", "9"], ["blue", "6"]] as const)("accepts matching %s card", (color, value) => expect(canPlayCard(card(color, value), state([]))).toBe(true));
  it("rejects a non-matching card", () => expect(canPlayCard(card("green", "4"), state([]))).toBe(false));
  it("plays a Wild only after its owner chooses a valid color", () => { const wild = card(null, "wild"); const played = playCard(state([wild, card("red", "1")]), "you", wild.id); expect(played.awaitingColorFor).toBe("you"); expect(() => drawCard(played, "you")).toThrow(); const chosen = selectWildColor(played, "you", "blue"); expect(chosen.activeColor).toBe("blue"); expect(chosen.currentPlayerIndex).toBe(1); });
  it("adds and stacks draw twos", () => { const first = card("yellow", "draw2"); const second = card("red", "draw2"); let game = playCard(state([first, card("yellow", "1")], card("yellow", "5")), "you", first.id); game.players[1].hand = [second, card("red", "1")]; game = playCard(game, "lena", second.id); expect(game.pendingDrawCount).toBe(4); expect(game.drawStackType).toBe("drawTwo"); });
  it("allows +4 over a +2 then makes the stack +4 only", () => { const plus2 = card("yellow", "draw2"), plus4 = card(null, "wild4"), another2 = card("red", "draw2"); let game = playCard(state([plus2, card("yellow", "1")], card("yellow", "8")), "you", plus2.id); game.players[1].hand = [plus4, card("red", "1")]; game = playCard(game, "lena", plus4.id); expect(game.pendingDrawCount).toBe(6); expect(game.drawStackType).toBe("drawFour"); game = selectWildColor(game, "lena", "red"); game.players[2].hand = [another2]; expect(() => playCard(game, "milo", another2.id)).toThrow(); });
  it("rejects +2 over +4 and lets +4 stack", () => { const plus4 = card(null, "wild4"), plus2 = card("red", "draw2"), another4 = card(null, "wild4"); let game = playCard(state([plus4, card("red", "1")]), "you", plus4.id); game = selectWildColor(game, "you", "red"); game.players[1].hand = [plus2]; expect(() => playCard(game, "lena", plus2.id)).toThrow(); game.players[1].hand = [another4, card("red", "1")]; game = playCard(game, "lena", another4.id); expect(game.pendingDrawCount).toBe(8); });
  it("accepting a pending stack draws all cards and ends the turn", () => { const first = card("yellow", "draw2"); let game = playCard(state([first, card("yellow", "1")], card("yellow", "8")), "you", first.id); const before = game.players[1].hand.length; game = acceptPendingDraw(game, "lena"); expect(game.players[1].hand).toHaveLength(before + 2); expect(game.pendingDrawCount).toBe(0); expect(game.currentPlayerIndex).toBe(2); });
  it("skip skips the next player", () => { const skip = card("yellow", "skip"); expect(playCard(state([skip, card("yellow", "1")], card("yellow", "8")), "you", skip.id).currentPlayerIndex).toBe(2); });
  it("reverse changes direction and is a skip with two players", () => { const reverse = card("yellow", "reverse"); let game = state([reverse, card("yellow", "1")], card("yellow", "8")); game.players = game.players.slice(0, 2); game = playCard(game, "you", reverse.id); expect(game.direction).toBe(-1); expect(game.currentPlayerIndex).toBe(0); });
  it("plays ordered same-number combos and uses their final color", () => { const red = card("red", "6"), blue = card("blue", "6"), green = card("green", "6"); const game = playCards(state([red, blue, green]), "you", [red.id, blue.id, green.id]); expect(game.activeColor).toBe("green"); expect(game.discardPile.slice(-3).map(item => item.id)).toEqual([red.id, blue.id, green.id]); });
  it("rejects mixed-value, special, and invalid-first combos", () => { const six = card("red", "6"), seven = card("blue", "7"), skip = card("yellow", "skip"), five = card("red", "5"); expect(() => playCards(state([six, seven]), "you", [six.id, seven.id])).toThrow(); expect(() => playCards(state([skip]), "you", [skip.id])).toThrow(); expect(() => playCards(state([five]), "you", [five.id])).toThrow(); });
  it("reshuffles all but the top discard when the draw pile is empty", () => { const old = card("green", "4"), top = card("yellow", "6"); const game = state([], top); game.drawPile = []; game.discardPile = [old, top]; const result = drawCard(game, "you"); expect(result.discardPile).toEqual([top]); expect(result.players[0].hand).toEqual([old]); });
  it("recognizes winners from one card or a combo and blocks later actions", () => { const one = card("yellow", "6"); const finished = playCard(state([one]), "you", one.id); expect(finished.winnerId).toBe("you"); expect(() => drawCard(finished, "you")).toThrow(); const red = card("red", "6"), blue = card("blue", "6"); expect(playCards(state([red, blue]), "you", [red.id, blue.id]).winnerId).toBe("you"); });
  it("rejects actions out of turn, duplicate cards, and invalid color selection", () => { const six = card("yellow", "6"); expect(() => playCard(state([six]), "lena", six.id)).toThrow(); expect(() => playCards(state([six]), "you", [six.id, six.id])).toThrow(); const wildCard = card(null, "wild"); const wild = playCard(state([wildCard, card("red", "2")]), "you", wildCard.id); expect(() => selectWildColor(wild, "lena", "red")).toThrow(); });
  it("creates a complete 108-card game", () => { const game = createGame(); expect(game.players).toHaveLength(3); expect(game.players.reduce((sum, player) => sum + player.hand.length, 0) + game.drawPile.length + game.discardPile.length).toBe(108); });
  it("allows a wild draw four only when the player has no active-color card", () => {
    const game = state([card(null, "wild4")], card("green", "9"));
    expect(canPlayCard(game.players[0].hand[0], game)).toBe(true);
    game.players[0].hand.push(card("green", "2"));
    expect(canPlayCard(game.players[0].hand[0], game)).toBe(false);
  });
  it("allows only draw cards while a draw-two stack is active", () => { const game = state([]); game.pendingDrawCount = 2; game.drawStackType = "drawTwo"; expect(canPlayCard(card("red", "draw2"), game)).toBe(true); expect(canPlayCard(card("yellow", "4"), game)).toBe(false); });
  it("allows only +4 while a draw-four stack is active", () => { const game = state([]); game.pendingDrawCount = 4; game.drawStackType = "drawFour"; expect(canPlayCard(card(null, "wild4"), game)).toBe(true); expect(canPlayCard(card("yellow", "draw2"), game)).toBe(false); });
  it("ends the turn after drawing an unplayable card", () => { const game = state([]); game.drawPile = [card("red", "1")]; expect(drawCard(game, "you").currentPlayerIndex).toBe(1); });
  it("keeps the turn after drawing a playable card", () => { const game = state([]); game.drawPile = [card("yellow", "2")]; const result = drawCard(game, "you"); expect(result.currentPlayerIndex).toBe(0); expect(result.hasDrawnCard).toBe(true); });
  it("prevents a second ordinary draw in the same turn", () => { const game = state([]); game.drawPile = [card("yellow", "2"), card("yellow", "3")]; expect(() => drawCard(drawCard(game, "you"), "you")).toThrow(); });
  it("does not let a player play a card they do not own", () => { const game = state([]); expect(() => playCard(game, "you", "not-in-hand")).toThrow(); });
  it("keeps the final special-card rule deterministic by declaring its player the winner", () => { const skip = card("yellow", "skip"); const result = playCard(state([skip], card("yellow", "8")), "you", skip.id); expect(result.gameStatus).toBe("finished"); expect(result.currentPlayerIndex).toBe(0); });
});
